@startuml
    title Model

    class ComputationTask
    class ComputationApplication
    class ComputationInput
    class ComputationStep
    class ComputationStepPackage
    class ComputationStepParam
    class Computation
    class Machine
    class MachineMetrics
    class MachineMetricValue

    ComputationTask *-- ComputationApplication
    ComputationTask o-- ComputationInput
    ComputationInput ..> ComputationApplication
    ComputationStepPackage *- "1..*" ComputationStep
    ComputationStep o-- "0..*" ComputationStepParam
    ComputationStep ..> ComputationApplication
    Computation *-- "1"ComputationStepPackage
    Computation *-- "1" ComputationInput
    Machine o-- MachineMetrics
    MachineMetrics o-- MachineMetricValue
@enduml