@startuml

skinparam componentStyle uml2

skinparam actor {
    BackgroundColor<<Machine>> Brown
}

actor "App User" as AU
actor Developer as AD
actor Supplier as AS
actor Administrator as AA

AA -le-|> AU

component Launcher as CLa
component Library as CLi
component Logger as CLo
component "Machine Manager" as CM
component Payments as CP
component Machine as CMa
component "OAuth Server" as CA

interface "/logger/launcher/" as ICLoCLa
interface "/logger/machine/" as ICLoCMa
interface "/machine-manager/machines/" as ICMCMa
interface "/library/admin/" as ICLiAA
interface "/machine-manager/admin/" as ICMAA
interface "/machine-manager/launcher/" as ICMCLa
interface "/library/launcher/" as ICLiCLa
interface "/payments/launcher/" as ICPCLa
interface "/payments/machine-manager/" as ICPCM
interface "/library/dev/" as ICLiAD
interface "/machine-manager/management/" as ICMAS
interface "/launcher/user/" as ICLaAU
interface "/machine/manager/" as ICMaCM

AD -ri-> ICLiAD
ICLiAD -ri- CLi

AS -up-> ICMAS
ICMAS -up- CM

AU -le-> ICLaAU
ICLaAU -le- CLa

CLi -do- ICLiCLa
ICLiCLa )-do- CLa

CLa -do-( ICMCLa
ICMCLa -do- CM

CM -do- ICMCMa
ICMCMa )-do- CMa
CM -do-( ICMaCM
ICMaCM -do- CMa

CMa <-ri- AS

CLi -do- ICLiAA
AA -up-> ICLiAA
CM --up- ICMAA
AA -do-> ICMAA

CP -do- ICPCLa
ICPCLa )-do- CLa

CP -do- ICPCM
CM -up-( ICPCM

CLa -do-> ICLoCLa
ICLoCLa -do- CLo
CLo -do- ICLoCMa
ICLoCMa <-do- CMa

@enduml
