@startuml

skinparam componentStyle uml2

skinparam actor {
    BackgroundColor<<Machine>> Brown
}

actor "App User" as AU
actor Developer as AD
actor Supplier as AS
actor Administrator as AA

AA -le-|> AU

component Launcher as CLa
component Library as CLi
component Logger as CLo
component "Machine Manager" as CM
component Payments as CP
component Cluster as CC
component Auth as CA

interface " " as ICLoCLa
interface " " as ICLoCC
interface " " as ICMAC
interface "Admin API" as ICLiAA
interface "Admin API" as ICMAA
interface " " as ICMCLa
interface " " as ICLiCLa
interface " " as ICPCLa
interface " " as ICPCM
interface "Dev API" as ICLiAD
interface "Supplier API" as ICMAS
interface "App User API" as ICLaAU
interface "Cluster API" as ICCCM
interface "Cluster CLI" as ICCAS

artifact "Application" as ArApp <<artifact>>

AD -ri-> ICLiAD
ICLiAD -ri- CLi

AS -up-> ICMAS
ICMAS -up- CM

AU -le-> ICLaAU
ICLaAU -le- CLa

CLi -do- ICLiCLa
ICLiCLa )-do- CLa

CLa -do-( ICMCLa
ICMCLa -do- CM

CM -do- ICMAC
ICMAC )-do- CC
CM -do-( ICCCM
ICCCM -do- CC

CC -ri- ICCAS
ICCAS <-ri- AS

CLi .do.> ArApp : <<create>>
CM .up.> ArApp : <<use>>

CLi -do- ICLiAA
AA -up-> ICLiAA
CM -up- ICMAA
AA -ri-> ICMAA

CP -do- ICPCLa
ICPCLa )-do- CLa

CP -do- ICPCM
CM -up-( ICPCM

CLa -do-> ICLoCLa
ICLoCLa -do- CLo
CLo -do- ICLoCC
ICLoCC <-do- CC

@enduml